name: Publish to Docker
on:
  push:
    branches:
      - main
permissions:
  packages: write
  contents: read
jobs:
  publish:
    name: build and publish docker container
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Add your test steps here if needed...
      - name: Test run
        run: echo::"Run test here"
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/TatsianaLemeshava/publish-packages/game
          tags: type=sha

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Docker Build 
      #  run: |
      #    docker build --no-cache -t testgithubactions .        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
   
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
